#!/bin/bash
# configure ESP ruby 1.8.7p352 build for workstation -- 5/8/17 brent@mbari.org
# for gcc x86 add:
#  -fno-stack-protector
# to CFLAGS
# also note that gcc >=4.7 requires -fno-tree-dce
: ${CFLAGS:="-O2 -g -Wclobbered -fno-stack-protector"}
: ${CXXFLAGS:=$CFLAGS}
for mod in mbarilib termios .; do
  [ -r $mod/Makefile ] && make -C $mod MINIRUBY=miniruby distclean
done
export CC CFLAGS CXXFLAGS
rm -f ext/readline/libreadline.so*
[ `which dpkg-architecture` ] && {
  lib="/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH`"
    #link Ruby readline extension with libreadline.5
  [ "$readline5" ] || readline5=$lib/libreadline.so.5
  if [ -r $readline5 ]; then
    ln -s $readline5 ext/readline/libreadline.so || exit $?
  else
    echo "WARNING:  Missing $readline5  (version 6 is incompatible)" >&2
    sleep 5
  fi

  #find the proper tcl support file in Debian's multiarch scheme
  tcfg=
  usr="/usr$lib"
  [ -r "$usr/tclConfig.sh" ] &&
    tcfg="--with-tclConfig-file=$usr/tclConfig.sh"
  [ -r "$usr/tkConfig.sh" ] &&
    tcfg="$tcfg --with-tkConfig-file=$usr/tkConfig.sh"
}
rm -f config.cache configure `find ext -name Makefile` &&
autoconf && exec configure --prefix=/opt/mbari \
  --enable-mbari-api --enable-pthread --disable-ucontext $tcfg $@